# Set up the environment to build the cc-ras-runner plugin
FROM ghcr.io/usace-cloud-compute/cc-hdf5-ras-base:v1.0.0 AS builder

ARG RAS_DEPLOYMENT=EngineOnly
ARG RAS_VERSION=HEC-RAS_660_Linux
ARG RAS_ARCHIVE=${RAS_VERSION}_${RAS_DEPLOYMENT}.zip
ARG NEXUS_RAS_URL=https://www.hec.usace.army.mil/nexus/repository/cloud-wat-resources/ras/${RAS_ARCHIVE}
ARG GOVERSION=1.24.12
ARG GOBINARCH=linux-amd64
ARG HDF5_PREFIX=/usr/local/lib/hdf5

ENV GOROOT=/go
ENV GOPATH=/src/go
ENV PATH=/go/bin:$PATH
ENV CGO_ENABLED=1
ENV CGO_CFLAGS=-I${HDF5_PREFIX}/include
ENV CGO_LDFLAGS=-L${HDF5_PREFIX}/lib
ENV LD_LIBRARY_PATH=${HDF5_PREFIX}/lib

RUN mkdir -p /ras /src/ras-runner && \
    wget "${NEXUS_RAS_URL}" -O "/${RAS_ARCHIVE}" && \
    unzip "/${RAS_ARCHIVE}" -d / && \
    mv "/${RAS_VERSION}_${RAS_DEPLOYMENT}/libs" /ras/libs && \
    mv "/${RAS_VERSION}_${RAS_DEPLOYMENT}/bin" /ras/bin && \
    chmod -R +x /ras/* && \
    wget "https://go.dev/dl/go${GOVERSION}.${GOBINARCH}.tar.gz" -O "/go${GOVERSION}.${GOBINARCH}.tar.gz" && \
    tar -xzf "/go${GOVERSION}.${GOBINARCH}.tar.gz" -C /

COPY ./ /src/ras-runner

RUN mv /src/ras-runner/runScripts/${RAS_VERSION}/* /src/ras-runner/

RUN echo "CGO_CFLAGS=$CGO_CFLAGS" && \
    echo "CGO_LDFLAGS=$CGO_LDFLAGS" && \
    echo "Checking HDF5 headers and libs..." && \
    test -f "${HDF5_PREFIX}/include/hdf5.h" && \
    ls -la "${HDF5_PREFIX}/include" && \
    ls -la "${HDF5_PREFIX}/lib"

RUN cd /src/ras-runner && \
    go env && \
    go mod download && \
    go build -v -x -work -o ras-runner 2>&1

FROM rockylinux:8 AS prod

ARG HDF5_PREFIX=/usr/local/lib/hdf5
ENV PATH=/hdf/bin:/ras/bin:/ras:$PATH
ENV LD_LIBRARY_PATH=${HDF5_PREFIX}/lib

RUN mkdir -p /sim/model

COPY --from=builder /ras /ras
COPY --from=builder /src/ras-runner/ras-runner /ras/ras-runner
COPY --from=builder /hdf /hdf
COPY --from=builder /src/ras-runner/run-geom-preproc.sh /ras/
COPY --from=builder /src/ras-runner/run-model.sh /ras/

RUN chmod +x /ras/run-model.sh /ras/run-geom-preproc.sh /ras/ras-runner

CMD ["/ras/ras-runner"]