#Set up the environment to build the cc-ras-runner plugin
FROM ghcr.io/usace-cloud-compute/cc-hdf5-ras-base:v1.0.0 as builder

#names specific to artifacts downloaded from cloud-wat-resources on the HEC Nexus.  Replace version number in all args. Currently available 610,631,641. -bbb 20240229
ARG RAS_DEPLOYMENT=EngineOnly
ARG RAS_VERSION=HEC-RAS_641_Linux
ARG RAS_ARCHIVE=${RAS_VERSION}_${RAS_DEPLOYMENT}.zip
ARG NEXUS_RAS_URL=https://www.hec.usace.army.mil/nexus/repository/cloud-wat-resources/ras/${RAS_ARCHIVE}
ARG GOVERSION=1.24.12
ARG GOBINARCH=linux-amd64
ARG HDF5_SRC_URL=https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/downloads
ARG HDF5_VERSION=1.14.5

ENV GOROOT=/go
ENV GOPATH=/src/go
ENV PATH=/go/bin:$PATH
ENV HDF5_PREFIX=/usr/local/lib/hdf5
ENV CGO_CFLAGS="-I${HDF5_PREFIX}/include"
ENV CGO_LDFLAGS="-L${HDF5_PREFIX}/lib -lhdf5 -lhdf5_hl"

RUN mkdir -p /ras/libs
RUN mkdir -p /ras/bin

RUN yum -y update &&\
    yum -y install epel-release &&\
    yum -y install --skip-broken git gdal-devel gcc make

RUN wget ${HDF5_SRC_URL}/hdf5-${HDF5_VERSION}.tar.gz &&\
    tar -xvzf /hdf5-${HDF5_VERSION}.tar.gz &&\ 
    cd /hdf5-${HDF5_VERSION} &&\
    ./configure --prefix=${HDF5_PREFIX} --with-default-api-version=v110 --enable-shared --enable-ros3-vfd --enable-hl &&\
    make &&\
    make install

RUN wget ${NEXUS_RAS_URL} &&\ 
    unzip ${RAS_ARCHIVE} &&\
    mv ${RAS_VERSION}_${RAS_DEPLOYMENT}/libs /ras/libs &&\
    mv ${RAS_VERSION}_${RAS_DEPLOYMENT}/bin /ras/bin &&\
    chmod -R +x /ras/* &&\ 
    wget https://go.dev/dl/go${GOVERSION}.${GOBINARCH}.tar.gz -P / &&\
    tar -xvzf go${GOVERSION}.${GOBINARCH}.tar.gz -C / &&\
    mkdir -p src/ras-runner 

COPY ./ /src/ras-runner

RUN mv /src/ras-runner/runScripts/${RAS_VERSION}/* /src/ras-runner 

RUN cd /src/ras-runner &&\
    go mod tidy &&\
    go build 


FROM rockylinux:8 as prod
ARG HDF5_PREFIX=/usr/local/lib/hdf5
ENV PATH=${HDF5_PREFIX}/bin:/ras/bin:/ras:$PATH
ENV LD_LIBRARY_PATH=${HDF5_PREFIX}/lib

RUN mkdir -p /sim/model

#RAS Binaries
COPY --from=builder /ras /ras
#cc-ras-runner binary
COPY --from=builder /src/ras-runner/ras-runner /ras/ras-runner
#hdf binaries
COPY --from=builder ${HDF5_PREFIX} ${HDF5_PREFIX}
#geom preproc script
COPY --from=builder /src/ras-runner/run-geom-preproc.sh /ras/
#model run script
COPY --from=builder /src/ras-runner/run-model.sh /ras/

RUN chmod +x /ras/run-model.sh &&\
    chmod +x /ras/run-geom-preproc.sh

CMD ["/ras/ras-runner"]